version: '3.6'

networks:
  elk-network:
    driver: bridge
  api-network:
    driver: bridge

services:
  elasticsearch:
    container_name: elasticsearch
    image: bitnami/elasticsearch:7
    ports:
      - 9200:9200
      - 9300:9300
    networks: 
      - api-network
      - stack-elastic-network
    volumes:
      - elasticsearch_data:/bitnami

  kibana:
    container_name: kibana
    image: bitnami/kibana:7
    ports:
      - 5600:5600
      - 5601:5601
    networks: 
      - stack-elastic-network
    volumes:
      - kibana_data:/bitnami
    depends_on:
        - elasticsearch
        - logstash

  logstash:
    container_name: logstash
    image: bitnami/logstash:7
    ports:
      - 7070:8080
    networks: 
      - api-network
      - stack-elastic-network
    volumes:
      - logstash_data:/bitnami
    depends_on:
      - elasticsearch

volumes:
  - elasticsearch_data
  - kibana_data
  - logstash_data
